config/routes.rb
Rails.application.routes.draw do

  root 'public/homes#top'

  #ユーザー用
  devise_for :users,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

 scope module: :public do

   post '/homes/guest_sign_in', to: 'homes#new_guest'
   get 'users/unsubscribe'=> 'users#unsubscribe',as: "unsubscribe"
   get 'search' => 'searches#index'

  resources :users do
   resource :relationships, only:[:create,:destroy]
   get :followings, on: :member
   get :followers,  on: :member
   member do
     resources :favorites,      only: [:index]
   end
  end
  resources :works do
   resource :favorites,     only: [:create,:destroy]
   resources :comments,      only: [:index,:create,:destroy] do
    resources :reports,       only: [:new,:create]
   end
  end

  resources :ranks,         only: [:index]
  resources :follows,       only: [:index,:create,:destroy]

 end


  devise_for :admins, controllers: {
  sessions: "admin/sessions"
}

 namespace :admin do

   get 'admin' => 'homes#top'
   get 'search' => 'searches#index'
   get 'users/unsubscribe'=> 'users#unsubscribe',as: "unsubscribe"

   resources :reports,      only: [:index,:destroy]
   resources :works
   resources :users

 end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :work
  belongs_to :user
  has_many :reports,dependent: :destroy
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  
  belongs_to :work
  belongs_to :user
  
  validates_uniqueness_of :work_id, scope: :user_id
  
end

app/models/follow.rb
class Follow < ApplicationRecord
  
  belongs_to :user
  
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :following,class_name: 'User'
  belongs_to :follower,class_name: 'User'
end

app/models/report.rb
class Report < ApplicationRecord
  
  belongs_to :work
  belongs_to :user
  belongs_to :comment
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :works ,dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :reports, dependent: :destroy
  has_many :follows, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :relationships,foreign_key: :following_id
  has_many :followings,through: :relationships, source: :follower
  has_many :reverse_of_relationships,class_name:'Relationship',foreign_key: :follower_id
  has_many :followers,through: :reverse_of_relationships, source: :following

  has_one_attached :image

  validates :name, presence: true
  
  def is_followed_by?(user)
    reverse_of_relationships.find_by(following_id: user.id).present?
  end

  def already_favorited?(work)
    self.favorites.exists?(work_id: work.id)
  end
  
  def is_guest?
    if self.email != "guest@example.com"
      return true
    end
    return false
  end

  def self.looks(search, word)
    
      if word.blank?
        return
      end
    
    if search == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?","%#{word}%")
    else
      @user = User.all
    end
    
  end

end

app/models/work.rb
class Work < ApplicationRecord

  belongs_to :user
  has_many :comments ,dependent: :destroy
  has_many :reports, dependent: :destroy
  has_many :favorites ,dependent: :destroy

  has_one_attached :image

  validates :title ,presence: true
  validates :image, presence: true

    def self.looks(search, word)

      if word.blank?
        return
      end

      if search == "perfect_match"
        @work = Work.where("title LIKE? OR genre LIKE?" ,"#{word}","#{word}")
      elsif search == "partial_match"
        @work = Work.where("title LIKE? OR genre LIKE?" ,"%#{word}%","%#{word}%")
      else
        @work = Work.all
      end

    end

end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < ApplicationController
  
  before_action :authenticate_admin!

  def destroy
    @comment = Comment.find(params[:id])
    @comment.delete
    redirect_to admin_reports_path
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  
  before_action :authenticate_admin!

  def top
    @users = User.page(params[:page])
  end

end

app/controllers/admin/reports_controller.rb
class Admin::ReportsController < ApplicationController
  
  before_action :authenticate_admin!

  def index
    @reports = Report.all.order(created_at: :desc)
  end

  def destroy
    @report = Report.find(params[:id])
    @report.delete
    redirect_to admin_reports_path
  end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  
  before_action :authenticate_admin!
  
  def edit
    @user = User.find(params[:id])
  end

  def show
    @user = User.find(params[:id])
    @works = @user.works.page(params[:page]).order(created_at: :desc)
  end

  def update
   @user = User.find(params[:id])
   @user.update(user_params)
   redirect_to admin_user_path(@user)
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to admin_admin_path
  end

  def unsubscribe
    @user = User.find(params[:id])
  end


  def user_params
    params.require(:user).permit(:image,:name,:introduction,:email)
  end
end

app/controllers/admin/works_controller.rb
class Admin::WorksController < ApplicationController

  before_action :authenticate_admin!

  def index
    @works = Work.page(params[:page]).order(created_at: :desc)
  end

  def show
    @work = Work.find(params[:id])
    @comments = @work.comments.page(params[:page]).order(created_at: :desc)
  end

  def edit
    @work = Work.find(params[:id])
  end

  def destroy
    @work = Work.find(params[:id])
    @work.delete
    redirect_to works_path
  end

  def update
     @work = Work.find(params[:id])
     @work.update(work_params)
     redirect_to admin_work_path(@work.id)
  end

  def work_params
    params.require(:work).permit(:image,:work,:genre,:introduction)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

  def application
   @image = current_user.image
  end
  
  def public_or_guest
    if current_user.email == "guest@example.com"
      redirect_to works_path
    end
  end
  

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name,:image])
  end

end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/reports_helper.rb
module Admin::ReportsHelper
end

app/helpers/admin/searches_helper.rb
module Admin::SearchesHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/admin/works_helper.rb
module Admin::WorksHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/reports/index.html.erb
  <div class = "container">
    <div class = "row">
      <div class = "col-md-12">
    <h2>ユーザーからの通報</h2>
    <table class = "table">
        <thead>
          <tr>
            <th>通報されたコメント</th>
            <th>理由</th>
            <th></th>
          </tr>
        </thead>
   　　　 <tbody>
          <% @reports.each do |report| %>
          <tr>
            <td><%= report.comment.body %></td>
            <td><%= report.body %></td>
            <td><%=  link_to"削除する" ,admin_report_path(report.id),method: :delete%></td>
          </tr>
          <% end %>
        </tbody>
        </table>
      </div>
    </div>
  </div>

app/views/admin/users/edit.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-12">
    <h2 class="mb-3">ユーザー情報編集</h2>
      <% if @user.image.present? %>
        <%= image_tag @user.image , size: "200x200"%>
      <% end %>
      <%= form_with model:@user,url: admin_user_path(@user),method: "patch", id: "patch" do |f| %>
        <div class="m-3">
          <%= f.label :image, "プロフィール画像：" %><br/>
          <%= f.file_field :image, accept: "image/*" , class: "form-controll" %>
        </div>
        <div class="m-3">
          <%= f.label :name, "ユーザー名：" %><br/>
          <%= f.text_field :name %>
        </div>
        <div class="m-3">
          <%= f.label :introduction, "自己紹介：" %><br/>
          <%= f.text_area :introduction,size: "30x5" %>
        </div>
        <div class="m-3">
          <%= f.label :email, "メールアドレス：" %><br/>
          <%= f.text_area :email %>
        </div>
        <div class="m-3">
          <%= f.submit '変更を保存',form: "patch", class: "btn btn-primary mt-3 mb-3" %>
        </div>
          <% end %>
        <%= link_to "アカウントを削除", admin_unsubscribe_path(id: @user.id),class:"btn btn-danger ml-3" %>
    </div>
  </div>
</div>

app/views/admin/users/show.html.erb
<div class="container mt-5">
  <div class="row">
   <div class= "col-12">
      <% if @user != current_user %>
        <h2><i class="fa-regular fa-user"></i>ユーザーページ</h2><br/>
         ユーザー：<%= @user.name %><br/>
      <% end %>
      <div class="m-3">
       <% if @user.image.present? %>
          <%= image_tag @user.image, class: 'work-image'  %><br/>
       <% end %>
      </div>
      <% if @user.introduction.present? %>
        自己紹介<br/>
        ：<%= @user.introduction %><br/>
      <% end %>
      <%= link_to"ユーザー編集",edit_admin_user_path(@user),class:"btn btn-success mt-3" %><br/>
      <hr>
      <%= render 'common/latest_post' ,works: @works %>
   </div>
  </div>
</div>

app/views/admin/users/unsubscribe.html.erb
<div class="container mt-5">
 <div class="row">
   <div class="col-12">
    <h2>本当にアカウントを消去しますか？</h2><br>
      <%= link_to "はい",admin_user_path(@user),method: :delete ,class:"btn btn-primary m-5"%>
      <%= link_to "いいえ",admin_user_path(@user),class:"btn btn-danger" %>
   </div>
 </div>
</div>

app/views/admin/works/edit.html.erb
  <div class="container mt-5">
    <div class="row">
      <div class="col-6">
         <h3><i class="fa-sharp fa-solid fa-file-import"></i>作品編集</h3><br/>
          <%= image_tag @work.image, size: "150x150" %>
          <%= form_with model:@work,url: admin_work_path(@work.id),method: :patch do |f| %>
            <div class="field m-3">
              <%= f.label :"作品画像：" %><br>
              <%= f.file_field :image, accept: "image/*" %>
            </div>
            <div class="field m-3">
              <%= f.label :"作品名：" %><br>
              <%= f.text_field :title %>
            </div>
            <div class="field m-3">
              <%= f.label :"ジャンル：" %><br>
              <%= f.text_field :genre %>
            </div>
            <div class="field m-3">
              <%= f.label :"作品説明：" %><br>
              <%= f.text_area :introduction,size: "40x10" %>
            </div>
            <div class="actions">
              <%= f.submit "更新" ,class: "btn btn-success" %>
            </div>
          <% end %>
          <%= link_to "作品削除", admin_work_path(@work.id),method: :delete ,class:"btn btn-danger mt-2"%>
      </div>
    </div>
  </div>

app/views/admin/works/index.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-6">
      <h2>最新投稿一覧</h2><br/>
      <div>
        <%= render 'common/time_line', works: @works %>
      </div>
    </div>
  </div>
</div>

app/views/admin/works/show.html.erb
<div class="container mt-5">
     <h3><i class="fa-solid fa-palette"></i>作品詳細</h3><br/>
      ユーザー：
      <%= link_to admin_user_path(@work.user.id) do %>
        <%= @work.user.name %><br/>
      <% end %>
      <%= image_tag @work.image, class: 'work-image' %><br/>
      作品名：<%= @work.title %><br/>
      ジャンル：<%= @work.genre %><br/>
      作品説明：<%= @work.introduction %><br/>
      更新日：<%= @work.updated_at.strftime("%Y-%m-%D") %><br/>
      <%= link_to "編集・削除",edit_admin_work_path(@work),class:"btn btn-success mt-3" %><br/>
      <hr>
      <% if @comments.count > 0 %>
        <h4 class="mt-5 ">最新コメント</h4>
        <div class="wrapper_all">
        <% @comments.each do |comment| %>
          <div class="wrapper_middle">
            <div class="card-wrapper mt-2">
              <div class="d-block comment-card m-2">
                <div class="text-center">
                  <%= image_tag comment.user.image, size: "75x75" %>
                </div>
                <div class="text-center">
                  <small><%= comment.user.name.truncate(14) %></small>
                </div>
                <hr>
              <%= comment.body %>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
      <%= paginate @comments %>
  </div>