config/routes.rb
Rails.application.routes.draw do

  root 'public/homes#top'

  #ユーザー用
  devise_for :users,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

 scope module: :public do

   post '/homes/guest_sign_in', to: 'homes#new_guest'
   get 'users/unsubscribe'=> 'users#unsubscribe',as: "unsubscribe"
   get 'search' => 'searches#index'

  resources :users do
   resource :relationships, only:[:create,:destroy]
   get :followings, on: :member
   get :followers,  on: :member
   member do
     resources :favorites,      only: [:index]
   end
  end
  resources :works do
   resource :favorites,     only: [:create,:destroy]
   resources :comments,      only: [:index,:create,:destroy] do
    resources :reports,       only: [:new,:create]
   end
  end

  resources :ranks,         only: [:index]
  resources :follows,       only: [:index,:create,:destroy]

 end


  devise_for :admins, controllers: {
  sessions: "admin/sessions"
}

 namespace :admin do

   get 'admin' => 'homes#top'
   get 'search' => 'searches#index'
   get 'users/unsubscribe'=> 'users#unsubscribe',as: "unsubscribe"

   resources :reports,      only: [:index,:destroy]
   resources :works
   resources :users

 end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :work
  belongs_to :user
  has_many :reports,dependent: :destroy
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  
  belongs_to :work
  belongs_to :user
  
  validates_uniqueness_of :work_id, scope: :user_id
  
end

app/models/follow.rb
class Follow < ApplicationRecord
  
  belongs_to :user
  
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :following,class_name: 'User'
  belongs_to :follower,class_name: 'User'
end

app/models/report.rb
class Report < ApplicationRecord
  
  belongs_to :work
  belongs_to :user
  belongs_to :comment
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :works ,dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :reports, dependent: :destroy
  has_many :follows, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :relationships,foreign_key: :following_id
  has_many :followings,through: :relationships, source: :follower
  has_many :reverse_of_relationships,class_name:'Relationship',foreign_key: :follower_id
  has_many :followers,through: :reverse_of_relationships, source: :following

  has_one_attached :image

  validates :name, presence: true
  
  def is_followed_by?(user)
    reverse_of_relationships.find_by(following_id: user.id).present?
  end

  def already_favorited?(work)
    self.favorites.exists?(work_id: work.id)
  end
  
  def is_guest?
    if self.email != "guest@example.com"
      return true
    end
    return false
  end

  def self.looks(search, word)
    
      if word.blank?
        return
      end
    
    if search == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?","%#{word}%")
    else
      @user = User.all
    end
    
  end

end

app/models/work.rb
class Work < ApplicationRecord

  belongs_to :user
  has_many :comments ,dependent: :destroy
  has_many :reports, dependent: :destroy
  has_many :favorites ,dependent: :destroy

  has_one_attached :image

  validates :title ,presence: true
  validates :image, presence: true

    def self.looks(search, word)

      if word.blank?
        return
      end

      if search == "perfect_match"
        @work = Work.where("title LIKE? OR genre LIKE?" ,"#{word}","#{word}")
      elsif search == "partial_match"
        @work = Work.where("title LIKE? OR genre LIKE?" ,"%#{word}%","%#{word}%")
      else
        @work = Work.all
      end

    end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  
  before_action :authenticate_admin!

  def top
    @users = User.page(params[:page])
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  
  before_action :authenticate_admin!
  
  def edit
    @user = User.find(params[:id])
  end

  def show
    @user = User.find(params[:id])
    @works = @user.works.page(params[:page]).order(created_at: :desc)
  end

  def update
   @user = User.find(params[:id])
   @user.update(user_params)
   redirect_to admin_user_path(@user)
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to admin_admin_path
  end

  def unsubscribe
    @user = User.find(params[:id])
  end


  def user_params
    params.require(:user).permit(:image,:name,:introduction,:email)
  end
end

app/controllers/admin/works_controller.rb
class Admin::WorksController < ApplicationController

  before_action :authenticate_admin!

  def index
    @works = Work.page(params[:page]).order(created_at: :desc)
  end

  def show
    @work = Work.find(params[:id])
    @comments = @work.comments.page(params[:page]).order(created_at: :desc)
  end

  def edit
    @work = Work.find(params[:id])
  end

  def destroy
    @work = Work.find(params[:id])
    @work.delete
    redirect_to works_path
  end

  def update
     @work = Work.find(params[:id])
     @work.update(work_params)
     redirect_to admin_work_path(@work.id)
  end

  def work_params
    params.require(:work).permit(:image,:work,:genre,:introduction)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

  def application
   @image = current_user.image
  end
  
  def public_or_guest
    if current_user.email == "guest@example.com"
      redirect_to works_path
    end
  end
  

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name,:image])
  end

end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/reports_helper.rb
module Admin::ReportsHelper
end

app/helpers/admin/searches_helper.rb
module Admin::SearchesHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/admin/works_helper.rb
module Admin::WorksHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

app/views/common/_comments.html.erb
  <h4 class="mt-5 ">最新コメント</h4>
  <div class="wrapper_all">
    <% comments.each do |comment| %>
      <div class="wrapper_middle">
      <div class="card-wrapper mt-2">
      <div class="d-block comment-card">
      <div class="text-center">
        <%= image_tag comment.user.image, size: "75x75" %>
      </div>
      <div class="text-center">
      <small><%= comment.user.name.truncate(14) %></small>
      </div>
      <hr>
      <%= comment.body %>
      </div>
      </div>
      <div class="comment">
      <% if current_user.name != "guest" && current_user != nil && comment.user.id == current_user.id  %>
        <%= link_to"削除",work_comment_path(@work.id,comment.id),method: :delete,class:"btn btn-warning mt-2" %>
      <% else %>
        <%= link_to"報告", new_work_comment_report_path(@work,comment) ,class:"btn btn-danger mt-2" %>
      <% end %>
      </div>
      </div>
    <% end %>
  </div>
      <%= paginate comments %>

app/views/common/_follow.hrml.erb
 <table class = "table">
        <thead>
          <tr>
            <th>ユーザー名</th>
            <th>自己紹介</th>
            <th>フォロー/フォロー解除</th>
          </tr>
        </thead>
       <tbody>
          <% users.each do |user| %>
          <tr>
            <td><%= link_to user_path(user) do %>
              <%= user.name %>
            <% end %>
            </td>
            <td><%= user.introduction %></td>
            <td>
              <% if user != current_user || user.is_followed_by?(current_user) %>
                <%= link_to user_relationships_path(user),method: :delete do %>
                  <button class ="btn btn-danger">フォロー解除</button><br/>
                <% end %>
              <% else %>
                <%= link_to user_relationships_path(user),method: :post do %>
                  <button class ="btn btn-primary">フォロー</button><br/>
                <% end %>
              <% end %>
            </td>
          </tr>
          <% end %>
        </tbody>
        </table>

app/views/common/_follow.html.erb
 <table class = "table">
        <thead>
          <tr>
            <th>ユーザー名</th>
            <th>自己紹介</th>
            <th>フォロー/フォロー解除</th>
          </tr>
        </thead>
       <tbody>
          <% users.each do |user| %>
          <tr>
            <td><%= link_to user_path(user) do %>
              <%= user.name %>
            <% end %>
            </td>
            <td><%= user.introduction %></td>
            <td>
              <% if user != current_user || user.is_followed_by?(current_user) %>
                <%= link_to user_relationships_path(user),method: :delete do %>
                  <button class ="btn btn-danger">フォロー解除</button><br/>
                <% end %>
              <% else %>
                <%= link_to user_relationships_path(user),method: :post do %>
                  <button class ="btn btn-primary">フォロー</button><br/>
                <% end %>
              <% end %>
            </td>
          </tr>
          <% end %>
        </tbody>
        </table>

app/views/common/_latest_post.html.erb
<h4 class="mt-3"><最新投稿></h4><br/>
  投稿数  <%= works.count %><br/>
  <ul class="card-wrapper mt-3">
    <% works.each do |work| %>
      <li class="post-card" style="background-color: #CCE9FF">
        <% if user_signed_in? %>
          <%= link_to work_path(work.id) do %>
            <%= image_tag work.image, size: "200x200" %><br/>
           <% end %>
        <% elsif admin_signed_in? %>
          <%= link_to admin_work_path(work.id) do %>
            <%= image_tag work.image, size: "200x200" %><br/>
          <% end %>
        <% end %>
        作品名：<%= work.title.truncate(10) %><br/>
        <% if user_signed_in? && current_user.name != "guest" %>
          <% if current_user.already_favorited?(work) %>
            <%= link_to"❤", work_favorites_path(work.id), method: :delete %><br/>
          <% else %>
            <%= link_to"♡", work_favorites_path(work.id), method: :post %>
          <% end %>
        <% end %>
        <%= work.favorites.count %>いいね<br/>
        <% if work.genre.present? %>
          ジャンル：<%= work.genre.truncate(10) %><br/>
        <% end %>
      </li>
    <% end %>
  </ul>
  <%= paginate works %>

app/views/common/_search.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-12">
    <h2>検索結果</h2>
    <table class="table table-hover table-inverse">
      <% if @range == "ユーザー" %>
      <tbody>
        <% if @users.present? %>
          <% @users.each do |user| %>
          <tr>
            <td>ユーザー名：<br/>
              <%= link_to edit_admin_user_path(user.id) do %>
                <%= user.name %>
              <% end %>
            </td>
            <td>自己紹介：<br/><% user.introduction %></td>
            <td>プロフィール画像<br/>
              <% if user.image.attached? %>
                <%= image_tag user.image, size: "150x150" %>
              <% end %>
            </td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
    <% end %>
      <% if @range =="作品" %>
        <tbody>
          <% if @works.present? %>
            <% @works.each do |work| %>
            <tr>
              <td>作品名：<br/>
                <%= link_to work_path(work) do %>
                  <%= work.title %>
                <% end %>
              </td>
              <td>ジャンル：<br/><%= work.genre %></td>
              <td>作品説明：<br/><%= work.introduction %></td>
              <td><%= link_to work_path(work.id) do %>
                <%= image_tag work.image, size: "150x150" %><br/>
              <% end %>
              </td>
            </tr>
            <% end %>
          <% end %>
        </tbody>
      <% end %>
      <% if @range =="ジャンル" %>
        <tbody>
          <% if @genres.present? %>
            <% @genres.each do |genre| %>
            <tr>
              <td>作品名：<br/>
                <%= link_to work_path(genre) do %>
                  <%= genre.title %>
                <% end %>
              </td>
              <td>ジャンル：<br/><%= genre.genre %></td>
              <td>作品説明：<br/><%= genre.introduction %></td>
              <td><%= link_to work_path(genre.id) do %>
                <%= image_tag genre.image, size: "150x150" %><br/>
              <% end %>
              </td>
            </tr>
            <% end %>
          <% end %>
        </tbody>
      <% end %>
    </table>
      </div>
    </div>
  </div>

app/views/common/_search_bar.html.erb
 <% if user_signed_in? %>
   <div class="search_form">
    <%= form_with url: search_path, local: true, method: :get do |f| %>
      <%= f.text_field :word %>
      <%= f.select :range, options_for_select([['ユーザー'], ['作品'], ['ジャンル']]) %>
      <%= f.select :search, options_for_select([["完全一致","perfect_match"],["部分一致","partial_match"]]) %>
      <%= f.submit "検索", class: "btn btn-primary" %>
    <% end %>
   </div>
<% end %>
 <% if admin_signed_in? %>
   <div class="search_form">
    <%= form_with url: admin_search_path, local: true, method: :get do |f| %>
      <%= f.text_field :word %>
      <%= f.select :range, options_for_select([['ユーザー'], ['作品'], ['ジャンル']]) %>
      <%= f.select :search, options_for_select([["完全一致","perfect_match"],["部分一致","partial_match"]]) %>
      <%= f.submit "検索", class: "btn btn-primary" %>
    <% end %>
   </div>
<% end %>

app/views/common/_time_line.html.erb
<ul class="card-wrapper">
<% works.each do |work| %>
  <li class = "post-card" style="background-color: #CCE9FF" >
  ユーザー：<%= work.user.name.truncate(10) %></br>
  <% if user_signed_in? %>
    <%= link_to work_path(work.id) do %>
      <%= image_tag work.image, size: "200x200" %></br>
    <% end %>
  <% elsif admin_signed_in? %>
  <%= link_to admin_work_path(work.id) do %>
    <%= image_tag work.image, size: "200x200" %></br>
  <% end %>
<% end %>
作品名：<%= work.title.truncate(10) %></br>
  <% if user_signed_in? %>
    <% if current_user.name != "guest" %>
      <% if current_user.already_favorited?(work) %>
        <%= link_to"❤", work_favorites_path(work.id), method: :delete %></br>
      <% else %>
        <%= link_to"♡", work_favorites_path(work.id), method: :post %>
      <% end %>
    <% end %>
  <% end %>
    <%= work.favorites.count %>いいね</br>
    <% if work.genre.present? %>
      ジャンル：<%= work.genre.truncate(10) %></br>
    <% end %>
  </li>
<% end %>
</ul>
<%= paginate works %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ArtistsAgora</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/7f7a7e072f.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #FAA63F;">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
      <h1>Artist's Agora</h1><br/>
        <div class="ml-5">
          <% if user_signed_in? %>
            <%= image_tag current_user.image, size: "70x70" if current_user.image.present? %>
            <small><%= current_user.name.truncate(10) %></small>
          <% end %>
        </div>
        <ul class = "navbar-nav ml-auto">
          <% if admin_signed_in? %>
            <%= render 'common/search_bar'  %>
            <li  class="nav-item"> <%= link_to"ユーザー",admin_admin_path, class: "nav-link" %> </li>
            <li  class="nav-item"> <%= link_to"通報一覧",admin_reports_path, class: "nav-link" %> </li>
            <li  class="nav-item"> <%= link_to"タイムライン", admin_works_path, class: "nav-link" %> </li>
            <li  class="nav-item"><i class="fa-sharp fa-solid fa-right-from-bracket"><%= link_to"ログアウト", destroy_admin_session_path,method: :delete, class: "nav-link" %></i></li>
          <% elsif user_signed_in? %>
            <%= render 'common/search_bar'%>
            <li  class="nav-item"> <%= link_to"タイムライン", works_path, class: "nav-link" %> </li>
            <li  class="nav-item"> <%= link_to"ランキング", ranks_path, class: "nav-link" %> </li>
            <% if current_user.is_guest? %>
              <li  class="nav-item"> <%= link_to"新規投稿", new_work_path, class: "nav-link" %> </li>
              <li  class="nav-item"> <%= link_to"マイページ", user_path(current_user), class: "nav-link" %> </li>
            <% end %>
            <li  class="nav-item"><i class="fa-sharp fa-solid fa-right-from-bracket"><%= link_to"ログアウト",  destroy_user_session_path,method: :delete, class: "nav-link" %></i></li>
          <% else %>
            <li  class = "nav-item"><i class="fa-sharp fa-solid fa-right-to-bracket"><%= link_to"ログイン",new_user_session_path, class: "nav-link" %></i></li>
          <% end %>
        </ul>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>